package com.kirg.referencelinksystem.enums.offerEnums;

public enum OfferrorGroup {
PSYCHOLODZY_I_TERAPEUCI,
    SPOLECZNOSC,
    WLASCICIELE_DOMOW,
    WLASCICIELE_MIESZKAN,
    NAJEMCY_DOMOW_I_MIESZKAN,
    URZĘDY_I_INSTYTUCJE,
    PRZEDSIEBIORCY,
    SENIORZY,
    MLODZIEZ,
    RODZICE,
    ROLNICY,
    PRACOWNICY,
    STUDENCI,
    WYKLADOWCY_I_NAUKOWCY,
    REKTORZY,
    DYREKTORZY_SZKOL,
    ORGANIZACJE_POZARZADOWE,
    OSOBY_BEZROBOTNE,
    OSOBY_NIEPELNOSPRAWNE,
    INNA_GRUPA
}
