package com.kirg.referencelinksystem.enums.offerEnums;

public enum OfferCategory {
    Wspieranie,
    Organizacja,
    Zarabianie,
    Kierowanie,
    Promowanie,
    Komunikowanie,
    Uświadamianie,
    Naprawa,
    Hodowla,
    Poszukiwanie,
    Analiza_i_badania,
    Pomaganie_innym,
    Budowanie_zrozumienia,
    Dawanie_otuchy_innym,
    Łączenie_zasobów_i_możliwości,
    Przedsiębiorczość,
    Zarządzanie_zasobami,
    Przywództwo,
    Uważność,
    Synergia_w_działaniu,
    Uczciwość,
    Generowanie,
    Ochrona,
    Instruktaż,
    Nabywanie_kompetencji,
    Umiejętność_pracy_pod_presją_czasu,
    Dbałość_o_dobrą_atmosferę,
    Rozwiązywanie_konfliktów,
    Motywowanie_pracowników,
    Logiczne_myślenie,
    Motywacja_samorozwoju,
    Obsługa_technologii,
    Porada
}
