package com.kirg.referencelinksystem.enums.offerEnums;

public enum OfferArea {

    SWIADOMOSC_ZYCIA,
    NATURA_WOKOL_MNIE,
    FIRMA_I_ORGANIZACJA,
    USLUGI_I_WYKONASTWO,
    RELACJE_Z_RODZINA,
    RELACJE_ZE_ZNAJOMYMI,
    SCIEZKA_ARTYSTY,
    NARZEDZIA_I_SYSTEMY_PRACY,
    KOMUNIKACJA_ONLINE,
    KOMPUTER_I_TELEFON,
    INTERNET_I_NARZEDZIA,
    KOMUNIKACJA_MIEJSKA,
    POSTRZEGANIE_INNYCH,
    SZKOLA_I_ROZWOJ,
    SWIADOMA_UPRAWA_ROSLIN,
    ZWIERZETA_WOKOL_NAS,
    SWIADOME_I_ZDROWE_ZYWIENIE,
    DBALOSC_O_ZDROWIE,
    PASJA_I_AKTYWNOSCI

}
